# Generated by Django 4.2.6 on 2023-10-31 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('nominal_timestamp', models.DateTimeField()),
                ('daily_availability', models.FloatField()),
                ('monthly_availability', models.FloatField()),
                ('campaign_availability', models.FloatField()),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='availability_tracker.campaign')),
            ],
            options={
                'verbose_name_plural': 'Availabilities',
            },
        ),
    ]
