# Generated by Django 4.2.6 on 2023-11-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability_tracker', '0002_alter_availability_campaign_id_lidarmeasurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='is_data',
            field=models.BooleanField(default=False),
        ),
    ]
