# Generated by Django 4.2.6 on 2023-11-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability_tracker', '0003_availability_is_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='availability',
            name='hourly_availability',
            field=models.FloatField(default=0),
        ),
    ]
