# Generated by Django 4.2.6 on 2023-11-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability_tracker', '0004_availability_height_availability_hourly_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='campaign_availability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='daily_availability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='availability',
            name='hourly_availability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='monthly_availability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
